import type { Lang } from "@/app/lib/i18n";

type AboutStep = { title: string; body: string };
export type AboutContent = {
  metaTitle: string;
  metaDescription: string;
  eyebrow: string;
  title: string;
  intro: string;
  processTitle: string;
  steps: AboutStep[];
  riskTitle: string;
  riskBody: string;
  limitsTitle: string;
  limits: string[];
  commercialTitle: string;
  commercialBody: string;
  responsibleTitle: string;
  responsibleBody: string;
  legalLinksTitle: string;
  aiLink: string;
  affiliateLink: string;
  responsibleLink: string;
  contactLink: string;
};

export const ABOUT_CONTENT: Record<Lang, AboutContent> = {
  en: {
    metaTitle: "About MatchSignal and its prediction methodology", metaDescription: "How MatchSignal builds validated bookmaker-market candidates, anchors probability to market consensus and uses bounded AI analysis.", eyebrow: "Platform and methodology", title: "About MatchSignal", intro: "MatchSignal is an informational sports-analysis platform. It turns current bookmaker-market data into constrained, traceable candidates and explains the uncertainty around every published selection.", processTitle: "How the analysis works", steps: [
      { title: "1. Event and odds discovery", body: "The data pipeline identifies supported upcoming events and retrieves available bookmaker markets. Availability depends on schedules, coverage and freshness." },
      { title: "2. Code-generated market candidates", body: "Code groups matching outcomes into candidateIds. AI cannot create a free-form market, selection or displayed price." },
      { title: "3. Coverage validation", body: "A production candidate must be supported by at least three bookmakers, so thin or unmatched markets are excluded." },
      { title: "4. Market anchor", body: "Bookmaker prices form a market-consensus probability anchor. Margin-aware market math supplies the reference point rather than an arbitrary independent AI estimate." },
      { title: "5. Bounded AI adjustment", body: "AI may add contextual reasoning and a deliberately small, validated probability adjustment. The anchor and bounds prevent AI from manufacturing a large edge on its own." },
      { title: "6. candidateId selection", body: "AI selects only from the code-built candidateIds for that event. The selected market, selection and bookmaker depth remain tied to the same candidate." },
      { title: "7. Positive-value eligibility", body: "A selection is eligible for production only when its estimated value remains above zero after the bounded probability process and the available price are combined. Positive value is theoretical, not a guarantee." },
      { title: "8. Same-selection affiliate CTA", body: "A sportsbook call to action appears only when that partner offers the same validated market and selection. Commercial relationships are not inputs to candidate math, although partner display order may be commercially configured." },
    ], riskTitle: "Risk tiers", riskBody: "Low, Medium and High are comparative labels derived from factors such as the offered odds and bookmaker depth. They do not measure certainty: a Low label can lose, and every stake remains at risk.", limitsTitle: "Limits and freshness", limits: ["Odds and market availability can move after data collection.", "Bookmaker feeds, mapping and AI context may contain errors or omissions.", "The pipeline does not claim unsupported team statistics, injuries or lineup data that are not in its inputs.", "Sports outcomes remain random and every probability estimate can be wrong."], commercialTitle: "Commercial transparency", commercialBody: "MatchSignal may earn affiliate compensation. Affiliate relationships do not control candidate generation, market math or bounded probability calculations. Always verify the live price, operator eligibility and terms yourself.", responsibleTitle: "Informational use and responsible betting", responsibleBody: "MatchSignal is not a sportsbook and does not accept bets. Content is educational, not financial advice. Bet only where legal, only at the applicable adult age and only with money you can afford to lose.", legalLinksTitle: "More information", aiLink: "AI Disclaimer", affiliateLink: "Affiliate Disclosure", responsibleLink: "Responsible Gambling", contactLink: "Contact MatchSignal",
  },
  hu: {
    metaTitle: "A MatchSignal és előrejelzési módszertana", metaDescription: "Hogyan épít a MatchSignal validált fogadóirodai piacjelölteket, piaci konszenzushoz horgonyzott valószínűséget és korlátozott MI-elemzést.", eyebrow: "Platform és módszertan", title: "A MatchSignalról", intro: "A MatchSignal tájékoztató sportelemző platform. Az aktuális fogadóirodai piacadatokból korlátozott, visszakövethető jelölteket készít, és minden közzétett választás bizonytalanságát bemutatja.", processTitle: "Az elemzés folyamata", steps: [
      { title: "1. Esemény- és odds-felderítés", body: "Az adatfolyam támogatott közelgő eseményeket és elérhető fogadóirodai piacokat azonosít; a kínálat menetrendtől, lefedettségtől és frissességtől függ." },
      { title: "2. Kód által létrehozott piacjelöltek", body: "A kód az egyező kimeneteleket candidateId-kbe rendezi. Az MI nem hozhat létre szabad formájú piacot, választást vagy kijelzett árat." },
      { title: "3. Lefedettség-ellenőrzés", body: "Éles jelölthöz legalább három fogadóiroda szükséges; a gyenge vagy nem egyező piacok kiesnek." },
      { title: "4. Piaci horgony", body: "A fogadóirodai árak piaci konszenzusos valószínűségi horgonyt adnak. A marzsot figyelembe vevő matematika a viszonyítási pont, nem egy önkényes MI-becslés." },
      { title: "5. Korlátozott MI-módosítás", body: "Az MI kontextust és kismértékű, validált valószínűségi módosítást adhat. A horgony és a korlátok megakadályozzák, hogy önállóan nagy előnyt gyártson." },
      { title: "6. candidateId-kiválasztás", body: "Az MI csak az adott esemény kód által épített candidateId-i közül választ; a piac, választás és mélység ugyanahhoz a jelölthöz marad kötve." },
      { title: "7. Pozitív érték feltétele", body: "Csak akkor kerülhet élesbe, ha a korlátozott valószínűségi folyamat és az elérhető ár után a becsült érték nulla felett marad. Ez elméleti, nem garancia." },
      { title: "8. Azonos választású affiliate CTA", body: "Fogadóirodai CTA csak akkor jelenik meg, ha a partner ugyanazt a validált piacot és választást kínálja. A kapcsolat nem számítási input, bár a partnersorrend kereskedelmileg beállítható." },
    ], riskTitle: "Kockázati szintek", riskBody: "A Low, Medium és High összehasonlító címkék az odds és a fogadóirodai mélység alapján. Nem biztonsági ígéretek: a Low is veszíthet, minden tét kockázatos.", limitsTitle: "Korlátok és frissesség", limits: ["Az odds és elérhetőség az adatfelvétel után változhat.", "A feed, a leképezés és az MI-kontektsus hibás vagy hiányos lehet.", "A folyamat nem állít olyan csapatstatisztikát, sérülést vagy összeállítást, amely nincs a bemenetben.", "A sport kimenetele véletlenszerű; minden becslés tévedhet."], commercialTitle: "Kereskedelmi átláthatóság", commercialBody: "A MatchSignal affiliate díjazást kaphat. Ez nem irányítja a jelöltképzést, a piacmatematikát vagy a korlátozott számítást. Ellenőrizze az élő árat, jogosultságot és feltételeket.", responsibleTitle: "Tájékoztatás és felelős fogadás", responsibleBody: "A MatchSignal nem fogadóiroda és nem fogad tétet. A tartalom oktatási, nem pénzügyi tanács. Csak jogszerűen, megfelelő életkorban és elveszíthető pénzzel fogadjon.", legalLinksTitle: "További információ", aiLink: "MI-jogi nyilatkozat", affiliateLink: "Affiliate tájékoztató", responsibleLink: "Felelős szerencsejáték", contactLink: "Kapcsolat",
  },
  de: {
    metaTitle: "Über MatchSignal und die Vorhersagemethodik", metaDescription: "Validierte Marktkandidaten, Marktkonsens und begrenzte KI-Analyse bei MatchSignal.", eyebrow: "Plattform und Methodik", title: "Über MatchSignal", intro: "MatchSignal ist eine Informationsplattform für Sportanalysen. Aktuelle Buchmacherdaten werden in begrenzte, nachvollziehbare Kandidaten überführt; die Unsicherheit jedes Picks wird erklärt.", processTitle: "So funktioniert die Analyse", steps: [
      { title: "1. Ereignis- und Quotensuche", body: "Die Pipeline findet unterstützte kommende Ereignisse und verfügbare Märkte; Umfang hängt von Kalender, Abdeckung und Aktualität ab." },
      { title: "2. Codegenerierte Kandidaten", body: "Code bündelt passende Ausgänge in candidateIds. KI darf Markt, Auswahl oder Preis nicht frei erzeugen." },
      { title: "3. Abdeckungsprüfung", body: "Ein Produktionskandidat braucht mindestens drei Buchmacher; dünne oder unpassende Märkte werden ausgeschlossen." },
      { title: "4. Marktanker", body: "Buchmacherpreise bilden einen Konsensanker. Margenbewusste Marktmathematik ist die Referenz statt einer beliebigen KI-Schätzung." },
      { title: "5. Begrenzte KI-Anpassung", body: "KI kann Kontext und eine kleine validierte Wahrscheinlichkeitsänderung beitragen. Anker und Grenzen verhindern einen allein erzeugten großen Vorteil." },
      { title: "6. candidateId-Auswahl", body: "KI wählt nur codegebaute candidateIds des Ereignisses; Markt, Auswahl und Tiefe bleiben am selben Kandidaten." },
      { title: "7. Positive-Value-Bedingung", body: "Nur ein nach begrenztem Prozess und Preis weiterhin positiver geschätzter Wert ist produktionsfähig. Das ist theoretisch, keine Garantie." },
      { title: "8. Gleiche Auswahl im Affiliate-CTA", body: "Ein CTA erscheint nur, wenn der Partner denselben validierten Markt und dieselbe Auswahl anbietet. Beziehungen beeinflussen die Mathematik nicht; Reihenfolge kann kommerziell konfiguriert sein." },
    ], riskTitle: "Risikostufen", riskBody: "Low, Medium und High sind Vergleichslabels aus Quote und Buchmachertiefe, keine Sicherheit. Auch Low kann verlieren.", limitsTitle: "Grenzen und Aktualität", limits: ["Quoten und Märkte können sich nach Erfassung ändern.", "Feeds, Zuordnung und KI-Kontext können fehlerhaft sein.", "Nicht vorhandene Teamstatistiken, Verletzungen oder Aufstellungen werden nicht behauptet.", "Sport bleibt zufällig; jede Schätzung kann falsch sein."], commercialTitle: "Kommerzielle Transparenz", commercialBody: "Affiliate-Vergütung ist möglich, steuert aber weder Kandidaten noch Marktmathematik oder begrenzte Berechnung. Live-Preis, Berechtigung und Bedingungen selbst prüfen.", responsibleTitle: "Information und Verantwortung", responsibleBody: "MatchSignal ist kein Buchmacher und nimmt keine Wetten an. Inhalte sind Bildung, keine Finanzberatung. Nur legal, im Erwachsenenalter und mit tragbarem Verlust wetten.", legalLinksTitle: "Weitere Informationen", aiLink: "KI-Haftungsausschluss", affiliateLink: "Affiliate-Offenlegung", responsibleLink: "Verantwortungsvolles Glücksspiel", contactLink: "Kontakt",
  },
  fr: {
    metaTitle: "À propos de MatchSignal et de sa méthodologie", metaDescription: "Candidats validés, consensus de marché et analyse IA bornée de MatchSignal.", eyebrow: "Plateforme et méthodologie", title: "À propos de MatchSignal", intro: "MatchSignal est une plateforme informative d'analyse sportive. Les marchés actuels deviennent des candidats contraints et traçables, avec une explication de leur incertitude.", processTitle: "Fonctionnement de l'analyse", steps: [
      { title: "1. Découverte", body: "Le pipeline identifie événements et marchés disponibles ; le contenu dépend du calendrier, de la couverture et de la fraîcheur." }, { title: "2. Candidats générés par code", body: "Le code groupe les issues en candidateIds. L'IA ne crée librement ni marché, ni sélection, ni prix." }, { title: "3. Validation de couverture", body: "Un candidat de production exige au moins trois bookmakers ; les marchés trop minces sont exclus." }, { title: "4. Ancre de marché", body: "Les prix forment un consensus, avec un calcul tenant compte de la marge, plutôt qu'une estimation IA arbitraire." }, { title: "5. Ajustement IA borné", body: "L'IA peut ajouter contexte et petit ajustement validé ; l'ancre l'empêche de fabriquer seule un grand avantage." }, { title: "6. Choix du candidateId", body: "L'IA choisit uniquement parmi les candidateIds du code ; marché, sélection et profondeur restent liés." }, { title: "7. Valeur positive", body: "La valeur estimée doit rester supérieure à zéro après le processus borné et le prix. Elle reste théorique, sans garantie." }, { title: "8. CTA de même sélection", body: "Le CTA n'apparaît que si le partenaire offre le même marché et la même sélection. L'affiliation n'entre pas dans les calculs ; l'ordre peut être commercial." },
    ], riskTitle: "Niveaux de risque", riskBody: "Low, Medium et High comparent cote et profondeur, sans mesurer une certitude. Même Low peut perdre.", limitsTitle: "Limites et fraîcheur", limits: ["Cotes et disponibilité peuvent changer.", "Flux, correspondance et contexte IA peuvent être erronés.", "Aucune statistique, blessure ou composition absente des entrées n'est revendiquée.", "Tout résultat sportif et toute probabilité restent incertains."], commercialTitle: "Transparence commerciale", commercialBody: "Une rémunération affiliée est possible sans contrôler candidats, calculs ou ajustement borné. Vérifiez le prix, l'éligibilité et les conditions.", responsibleTitle: "Information et jeu responsable", responsibleBody: "MatchSignal n'est pas un bookmaker. Le contenu est éducatif, pas financier. Jouez seulement légalement, à l'âge requis et avec une somme perdable.", legalLinksTitle: "En savoir plus", aiLink: "Avertissement IA", affiliateLink: "Divulgation d'affiliation", responsibleLink: "Jeu responsable", contactLink: "Contact",
  },
  es: {
    metaTitle: "Sobre MatchSignal y su metodología", metaDescription: "Candidatos validados, consenso de mercado y análisis de IA acotado en MatchSignal.", eyebrow: "Plataforma y metodología", title: "Sobre MatchSignal", intro: "MatchSignal es una plataforma informativa de análisis deportivo. Convierte mercados actuales en candidatos limitados y trazables y explica su incertidumbre.", processTitle: "Cómo funciona el análisis", steps: [
      { title: "1. Descubrimiento", body: "El flujo identifica eventos y mercados; la oferta depende de calendario, cobertura y actualidad." }, { title: "2. Candidatos de código", body: "El código agrupa resultados en candidateIds. La IA no crea libremente mercado, selección o precio." }, { title: "3. Cobertura", body: "Producción exige al menos tres casas; mercados débiles o sin correspondencia se excluyen." }, { title: "4. Ancla de mercado", body: "Los precios forman consenso y la matemática considera el margen, en vez de una estimación arbitraria de IA." }, { title: "5. Ajuste acotado", body: "La IA añade contexto y un pequeño ajuste validado; los límites impiden fabricar sola una gran ventaja." }, { title: "6. Selección candidateId", body: "La IA elige solo candidateIds del código; mercado, selección y profundidad siguen unidos." }, { title: "7. Valor positivo", body: "La estimación debe quedar sobre cero tras proceso y precio. Es teórica y no garantiza resultados." }, { title: "8. CTA de la misma selección", body: "Solo aparece si el socio ofrece el mismo mercado/selección. La afiliación no entra en cálculos, aunque el orden puede ser comercial." },
    ], riskTitle: "Niveles de riesgo", riskBody: "Low, Medium y High comparan cuota y profundidad, no certeza. Un Low también pierde.", limitsTitle: "Límites y actualidad", limits: ["Cuotas y mercados pueden cambiar.", "Feeds, mapeo y contexto IA pueden fallar.", "No se afirman estadísticas, lesiones o alineaciones ausentes.", "Todo resultado y probabilidad siguen siendo inciertos."], commercialTitle: "Transparencia comercial", commercialBody: "Puede existir comisión sin controlar candidatos, matemáticas ni ajuste. Verifique precio, elegibilidad y términos.", responsibleTitle: "Información y responsabilidad", responsibleBody: "MatchSignal no acepta apuestas. Es educación, no asesoramiento financiero. Apueste solo legalmente, con edad y dinero que pueda perder.", legalLinksTitle: "Más información", aiLink: "Descargo de IA", affiliateLink: "Divulgación de afiliados", responsibleLink: "Juego responsable", contactLink: "Contacto",
  },
  it: {
    metaTitle: "MatchSignal e metodologia di previsione", metaDescription: "Candidati validati, consenso di mercato e analisi IA limitata.", eyebrow: "Piattaforma e metodologia", title: "Informazioni su MatchSignal", intro: "MatchSignal è una piattaforma informativa di analisi sportiva. Trasforma mercati attuali in candidati vincolati e tracciabili, spiegandone l'incertezza.", processTitle: "Come funziona l'analisi", steps: [
      { title: "1. Scoperta", body: "Il flusso identifica eventi e mercati; disponibilità dipende da calendario, copertura e freschezza." }, { title: "2. Candidati del codice", body: "Il codice raggruppa esiti in candidateIds. L'IA non crea liberamente mercato, selezione o prezzo." }, { title: "3. Copertura", body: "La produzione richiede almeno tre bookmaker; mercati sottili sono esclusi." }, { title: "4. Ancora di mercato", body: "I prezzi formano consenso e la matematica considera il margine, non una stima IA arbitraria." }, { title: "5. Aggiustamento limitato", body: "L'IA aggiunge contesto e un piccolo aggiustamento validato; i limiti impediscono un grande vantaggio autonomo." }, { title: "6. Scelta candidateId", body: "L'IA sceglie solo candidateIds del codice; mercato, selezione e profondità restano collegati." }, { title: "7. Valore positivo", body: "La stima deve restare sopra zero dopo processo e prezzo. È teorica, senza garanzia." }, { title: "8. CTA identico", body: "Appare solo se il partner offre lo stesso mercato e selezione. L'affiliazione non entra nei calcoli; l'ordine può essere commerciale." },
    ], riskTitle: "Livelli di rischio", riskBody: "Low, Medium e High confrontano quota e profondità, non la certezza. Anche Low può perdere.", limitsTitle: "Limiti e freschezza", limits: ["Quote e mercati cambiano.", "Feed, mapping e contesto IA possono sbagliare.", "Nessuna statistica, infortunio o formazione assente viene dichiarata.", "Risultati e probabilità restano incerti."], commercialTitle: "Trasparenza commerciale", commercialBody: "La commissione non controlla candidati, matematica o aggiustamento. Verificare prezzo, idoneità e termini.", responsibleTitle: "Informazione e responsabilità", responsibleBody: "MatchSignal non accetta scommesse. È educazione, non consulenza finanziaria. Scommettere solo legalmente, da adulti e con somme perdibili.", legalLinksTitle: "Altre informazioni", aiLink: "Disclaimer IA", affiliateLink: "Informativa affiliati", responsibleLink: "Gioco responsabile", contactLink: "Contatto",
  },
  pt: {
    metaTitle: "Sobre o MatchSignal e a metodologia", metaDescription: "Candidatos validados, consenso de mercado e análise IA limitada.", eyebrow: "Plataforma e metodologia", title: "Sobre o MatchSignal", intro: "O MatchSignal é uma plataforma informativa de análise desportiva. Converte mercados atuais em candidatos limitados e rastreáveis e explica a incerteza.", processTitle: "Como funciona a análise", steps: [
      { title: "1. Descoberta", body: "O fluxo identifica eventos e mercados; disponibilidade depende de calendário, cobertura e atualidade." }, { title: "2. Candidatos por código", body: "O código agrupa resultados em candidateIds. A IA não cria livremente mercado, seleção ou preço." }, { title: "3. Cobertura", body: "Produção exige pelo menos três casas; mercados fracos são excluídos." }, { title: "4. Âncora de mercado", body: "Os preços formam consenso e a matemática considera margem, não uma estimativa arbitrária de IA." }, { title: "5. Ajuste limitado", body: "A IA acrescenta contexto e pequeno ajuste validado; limites impedem vantagem grande autónoma." }, { title: "6. Escolha candidateId", body: "A IA escolhe só candidateIds do código; mercado, seleção e profundidade permanecem ligados." }, { title: "7. Valor positivo", body: "A estimativa deve ficar acima de zero após processo e preço. É teórica, não garantia." }, { title: "8. CTA igual", body: "Só aparece se o parceiro oferecer o mesmo mercado/seleção. A afiliação não entra nos cálculos; a ordem pode ser comercial." },
    ], riskTitle: "Níveis de risco", riskBody: "Low, Medium e High comparam odd e profundidade, não certeza. Low também pode perder.", limitsTitle: "Limites e atualidade", limits: ["Odds e mercados mudam.", "Feeds, mapeamento e contexto IA podem errar.", "Não se alegam estatísticas, lesões ou equipas ausentes.", "Resultados e probabilidades são incertos."], commercialTitle: "Transparência comercial", commercialBody: "A comissão não controla candidatos, matemática ou ajuste. Confirme preço, elegibilidade e termos.", responsibleTitle: "Informação e responsabilidade", responsibleBody: "O MatchSignal não aceita apostas. É educação, não aconselhamento financeiro. Aposte apenas legalmente, como adulto e com dinheiro que pode perder.", legalLinksTitle: "Mais informações", aiLink: "Aviso IA", affiliateLink: "Divulgação de afiliados", responsibleLink: "Jogo responsável", contactLink: "Contacto",
  },
  ar: {
    metaTitle: "حول MatchSignal ومنهجية التوقع", metaDescription: "مرشحون موثقون وإجماع سوق وتحليل ذكاء اصطناعي مقيّد.", eyebrow: "المنصة والمنهجية", title: "حول MatchSignal", intro: "MatchSignal منصة معلومات للتحليل الرياضي تحوّل الأسواق الحالية إلى مرشحين مقيدين قابلين للتتبع وتشرح عدم اليقين.", processTitle: "كيف يعمل التحليل", steps: [
      { title: "1. اكتشاف الأحداث", body: "يحدد المسار الأحداث والأسواق؛ ويتوقف التوافر على الجدول والتغطية والحداثة." }, { title: "2. مرشحو الكود", body: "يجمع الكود النتائج في candidateIds؛ ولا يخترع الذكاء الاصطناعي السوق أو الاختيار أو السعر." }, { title: "3. التغطية", body: "يتطلب الإنتاج ثلاث شركات على الأقل وتستبعد الأسواق الضعيفة." }, { title: "4. مرساة السوق", body: "تكوّن الأسعار إجماعًا وتحسب الرياضيات الهامش بدل تقدير عشوائي للذكاء الاصطناعي." }, { title: "5. تعديل محدود", body: "يضيف الذكاء الاصطناعي سياقًا وتعديلًا صغيرًا موثقًا؛ وتمنع الحدود صنع أفضلية كبيرة." }, { title: "6. اختيار candidateId", body: "يختار فقط من قائمة الكود؛ ويبقى السوق والاختيار والعمق مرتبطًا." }, { title: "7. قيمة إيجابية", body: "يجب أن تبقى القيمة فوق الصفر بعد العملية والسعر. هي نظرية وليست ضمانًا." }, { title: "8. CTA للاختيار نفسه", body: "لا يظهر إلا إذا قدم الشريك السوق والاختيار نفسيهما. الإحالة ليست في الحسابات وإن كان الترتيب تجاريًا." },
    ], riskTitle: "مستويات المخاطر", riskBody: "Low وMedium وHigh تقارن السعر والعمق ولا تعني اليقين؛ حتى Low قد يخسر.", limitsTitle: "الحدود والحداثة", limits: ["تتغير الأسعار والأسواق.", "قد تخطئ البيانات والربط وسياق الذكاء الاصطناعي.", "لا ندعي إحصاءات أو إصابات أو تشكيلات غير موجودة.", "كل نتيجة واحتمال غير يقيني."], commercialTitle: "الشفافية التجارية", commercialBody: "قد توجد عمولة لكنها لا تتحكم في المرشحين أو الرياضيات أو التعديل. تحقق من السعر والأهلية والشروط.", responsibleTitle: "المعلومات والمسؤولية", responsibleBody: "MatchSignal لا يقبل رهانات. المحتوى تعليمي وليس نصيحة مالية. راهن فقط حيث يسمح القانون وبالسن المناسب وبمال يمكنك خسارته.", legalLinksTitle: "معلومات إضافية", aiLink: "إخلاء مسؤولية الذكاء الاصطناعي", affiliateLink: "إفصاح الإحالة", responsibleLink: "المقامرة المسؤولة", contactLink: "الاتصال",
  },
  zh: {
    metaTitle: "关于 MatchSignal 及预测方法", metaDescription: "经验证市场候选、市场共识锚点和受限 AI 分析。", eyebrow: "平台与方法", title: "关于 MatchSignal", intro: "MatchSignal 是体育分析信息平台，将当前市场数据转为受约束、可追溯的候选并说明不确定性。", processTitle: "分析流程", steps: [
      { title: "1. 赛事与赔率发现", body: "流程发现支持的赛事和市场；可用性取决于赛程、覆盖和时效。" }, { title: "2. 代码生成候选", body: "代码将对应结果组成 candidateId；AI 不能自由生成市场、选择或价格。" }, { title: "3. 覆盖验证", body: "生产候选至少需三家博彩公司支持，薄弱市场被排除。" }, { title: "4. 市场锚点", body: "价格构成共识概率，考虑利润率的数学提供基准，而非任意 AI 估计。" }, { title: "5. 有限 AI 调整", body: "AI 可加入背景和小幅验证调整；锚点与边界防止独立制造大优势。" }, { title: "6. candidateId 选择", body: "AI 仅从代码列表选择；市场、选择与深度保持同一候选。" }, { title: "7. 正价值资格", body: "有限流程与可用价格结合后估计值仍须大于零。它是理论值，不保证结果。" }, { title: "8. 相同选择 CTA", body: "仅在合作方提供同一市场和选择时显示。联盟不参与计算，但展示顺序可商业配置。" },
    ], riskTitle: "风险等级", riskBody: "Low、Medium、High 比较赔率和深度，并非确定性；Low 也会失败。", limitsTitle: "局限与时效", limits: ["赔率与市场会变化。", "数据源、映射和 AI 背景可能出错。", "不会声称输入中没有的统计、伤病或阵容。", "任何结果和概率均不确定。"], commercialTitle: "商业透明度", commercialBody: "可能获得联盟佣金，但不控制候选、数学或有限调整。请核实实时价格、资格及条款。", responsibleTitle: "信息用途与责任", responsibleBody: "MatchSignal 不接受投注。内容是教育信息而非财务建议。仅在合法、达到年龄且金额可承受损失时投注。", legalLinksTitle: "更多信息", aiLink: "AI 免责声明", affiliateLink: "联盟披露", responsibleLink: "负责任博彩", contactLink: "联系",
  },
  ja: {
    metaTitle: "MatchSignal と予測手法", metaDescription: "検証済み市場候補、コンセンサス基準、限定 AI 分析。", eyebrow: "プラットフォームと手法", title: "MatchSignal について", intro: "MatchSignal はスポーツ分析情報サイトです。現在の市場データを制約付きで追跡可能な候補にし、不確実性を説明します。", processTitle: "分析の流れ", steps: [
      { title: "1. イベント発見", body: "対象イベントと市場を見つけ、提供状況は日程、範囲、鮮度に依存します。" }, { title: "2. コード生成候補", body: "コードが結果を candidateId にまとめ、AI は市場、選択、価格を自由生成できません。" }, { title: "3. カバレッジ検証", body: "本番候補は最低3社の支持が必要で、薄い市場は除外します。" }, { title: "4. 市場基準", body: "価格がコンセンサスを作り、マージンを考慮した数学が任意の AI 推定に代わる基準です。" }, { title: "5. 限定 AI 調整", body: "AI は文脈と小さな検証済み調整を加えられますが、大きな優位を単独生成できません。" }, { title: "6. candidateId 選択", body: "AI はコード一覧のみから選び、市場、選択、深度は同一候補に紐づきます。" }, { title: "7. 正価値条件", body: "限定処理と価格後も推定値が0超である必要があります。理論値で保証ではありません。" }, { title: "8. 同一選択 CTA", body: "提携先に同一市場・選択がある時のみ表示します。提携は計算に入らず、順序は商業設定の場合があります。" },
    ], riskTitle: "リスク区分", riskBody: "Low、Medium、High はオッズと深度の比較で、確実性ではありません。Low も負けます。", limitsTitle: "限界と鮮度", limits: ["オッズと市場は変動します。", "フィード、対応付け、AI 文脈は誤る場合があります。", "入力にない統計、負傷、先発情報は主張しません。", "結果と確率は常に不確実です。"], commercialTitle: "商業透明性", commercialBody: "報酬は候補、数学、限定調整を支配しません。ライブ価格、資格、条件を確認してください。", responsibleTitle: "情報利用と責任", responsibleBody: "MatchSignal は賭けを受けません。教育情報であり金融助言ではありません。適法な成人が失える資金のみで利用してください。", legalLinksTitle: "詳細", aiLink: "AI 免責事項", affiliateLink: "アフィリエイト開示", responsibleLink: "責任あるギャンブル", contactLink: "連絡先",
  },
  hi: {
    metaTitle: "MatchSignal और prediction methodology", metaDescription: "Validated market candidates, consensus anchor और bounded AI analysis।", eyebrow: "Platform और methodology", title: "MatchSignal के बारे में", intro: "MatchSignal informational sports-analysis platform है जो current market data को constrained, traceable candidates में बदलकर uncertainty समझाता है।", processTitle: "Analysis कैसे काम करता है", steps: [
      { title: "1. Event discovery", body: "Pipeline supported events/markets खोजती है; availability schedule, coverage और freshness पर है।" }, { title: "2. Code candidates", body: "Code outcomes को candidateIds में जोड़ता है; AI free-form market, selection या price नहीं बनाता।" }, { title: "3. Coverage validation", body: "Production candidate के लिए कम से कम तीन bookmakers चाहिए; thin markets हटते हैं।" }, { title: "4. Market anchor", body: "Prices consensus anchor देते हैं और margin-aware math reference है, arbitrary AI estimate नहीं।" }, { title: "5. Bounded AI", body: "AI context और छोटा validated adjustment दे सकता है; bounds बड़ा edge बनाने से रोकते हैं।" }, { title: "6. candidateId selection", body: "AI code list से ही चुनता है; market, selection और depth एक candidate से जुड़े रहते हैं।" }, { title: "7. Positive value", body: "Process और price के बाद estimated value zero से ऊपर रहना चाहिए। यह theoretical है, guarantee नहीं।" }, { title: "8. Same-selection CTA", body: "Partner पर वही validated market/selection होने पर ही CTA आता है। affiliation calculations में input नहीं, order commercial हो सकता है।" },
    ], riskTitle: "Risk tiers", riskBody: "Low, Medium, High odds और depth की तुलना हैं, certainty नहीं; Low भी हार सकता है।", limitsTitle: "Limits और freshness", limits: ["Odds/markets बदलते हैं।", "Feeds, mapping और AI context गलत हो सकते हैं।", "Absent stats, injuries या lineups का दावा नहीं।", "Outcomes और probabilities uncertain हैं।"], commercialTitle: "Commercial transparency", commercialBody: "Commission candidates, math या bounded adjustment नियंत्रित नहीं करती। live price, eligibility और terms जाँचें।", responsibleTitle: "Information और responsibility", responsibleBody: "MatchSignal bets स्वीकार नहीं करता। यह education है, financial advice नहीं। केवल legal age, lawful jurisdiction और affordable loss के साथ bet करें।", legalLinksTitle: "अधिक जानकारी", aiLink: "AI अस्वीकरण", affiliateLink: "एफिलिएट प्रकटीकरण", responsibleLink: "जिम्मेदार जुआ", contactLink: "संपर्क",
  },
};
