export const env = {
  CRON_SECRET: process.env.CRON_SECRET!,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY!,
  BLOB_READ_WRITE_TOKEN: process.env.BLOB_READ_WRITE_TOKEN!,
  UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL!,
  UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN!,
  INSTAGRAM_BUSINESS_ID: process.env.INSTAGRAM_BUSINESS_ID!,
  INSTAGRAM_ACCESS_TOKEN: process.env.INSTAGRAM_ACCESS_TOKEN!,
  FACEBOOK_PAGE_ID: process.env.FACEBOOK_PAGE_ID!,
  FACEBOOK_ACCESS_TOKEN: process.env.FACEBOOK_ACCESS_TOKEN!,
};