export const env = {
  UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL!,
  UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN!,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY!,
  SOCIAL_CRON_SECRET: process.env.SOCIAL_CRON_SECRET!,
  META_IG_USER_ID: process.env.META_IG_USER_ID!,
  META_PAGE_ID: process.env.META_PAGE_ID!,
  META_PAGE_ACCESS_TOKEN: process.env.META_PAGE_ACCESS_TOKEN!,
  PUBLIC_BASE_URL: process.env.PUBLIC_BASE_URL!,
};