import type { Lang } from "@/app/lib/i18n";

export const GUIDES_LABEL: Record<Lang, string> = {
  en: "Betting Guides",
  hu: "Fogadási útmutatók",
  de: "Wettleitfäden",
  fr: "Guides de paris",
  es: "Guías de apuestas",
  it: "Guide alle scommesse",
  pt: "Guias de apostas",
  ar: "أدلة المراهنات",
  zh: "投注指南",
  ja: "ベッティングガイド",
  hi: "बेटिंग गाइड",
};

export const RECOMMENDATION_LABEL: Record<Lang, string> = {
  en: "Recommendation",
  hu: "Ajánlás",
  de: "Empfehlung",
  fr: "Recommandation",
  es: "Recomendación",
  it: "Raccomandazione",
  pt: "Recomendação",
  ar: "التوصية",
  zh: "推荐",
  ja: "推奨",
  hi: "सिफारिश",
};

export const PRIVACY_COPY = {
  en: {
    ariaLabel: "Privacy and Consent Choices",
    title: "Privacy choices",
    intro: "We use necessary storage to operate MatchSignal. With your permission, we also use analytics to understand how the site is used and improve it. Advertising consent is managed separately where Google consent services are available.",
    customize: "Customize",
    necessaryOnly: "Necessary only",
    allowAnalytics: "Allow analytics",
    customizeTitle: "Customize Privacy Choices",
    close: "Close",
    necessary: "Necessary",
    alwaysActive: "Always Active",
    necessaryDesc: "Required for site navigation, security, and storing your consent preferences.",
    analytics: "Analytics (GA4)",
    analyticsDesc: "Helps us measure site traffic, page views, and feature usage to improve performance.",
    advertising: "Advertising (AdSense)",
    googleCmp: "Google CMP",
    advertisingDesc: "Advertising consent is managed separately via Google consent services where available.",
    savePreferences: "Save Preferences",
    cookieSettings: "Cookie Settings",
  },
  hu: {
    ariaLabel: "AdatvĂ©delmi Ă©s hozzĂˇjĂˇrulĂˇsi beĂˇllĂ­tĂˇsok",
    title: "AdatvĂ©delmi beĂˇllĂ­tĂˇsok",
    intro: "A MatchSignal mĹ±kĂ¶dĂ©sĂ©hez szĂĽksĂ©ges tĂˇrolĂˇst hasznĂˇlunk. Az Ă–n engedĂ©lyĂ©vel analitikĂˇt is hasznĂˇlunk az oldal hasznĂˇlatĂˇnak megĂ©rtĂ©sĂ©re Ă©s fejlesztĂ©sĂ©re. A hirdetĂ©si hozzĂˇjĂˇrulĂˇst kĂĽlĂ¶n kezeljĂĽk, ahol a Google hozzĂˇjĂˇrulĂˇsi szolgĂˇltatĂˇsai elĂ©rhetĹ‘k.",
    customize: "TestreszabĂˇs",
    necessaryOnly: "Csak szĂĽksĂ©ges",
    allowAnalytics: "Analitika engedĂ©lyezĂ©se",
    customizeTitle: "AdatvĂ©delmi beĂˇllĂ­tĂˇsok testreszabĂˇsa",
    close: "BezĂˇrĂˇs",
    necessary: "SzĂĽksĂ©ges",
    alwaysActive: "Mindig aktĂ­v",
    necessaryDesc: "Az oldal navigĂˇciĂłjĂˇhoz, biztonsĂˇgĂˇhoz Ă©s a hozzĂˇjĂˇrulĂˇsi beĂˇllĂ­tĂˇsok tĂˇrolĂˇsĂˇhoz szĂĽksĂ©ges.",
    analytics: "Analitika (GA4)",
    analyticsDesc: "SegĂ­t mĂ©rni az oldal forgalmĂˇt, az oldalmegtekintĂ©seket Ă©s a funkciĂłk hasznĂˇlatĂˇt a teljesĂ­tmĂ©ny javĂ­tĂˇsa Ă©rdekĂ©ben.",
    advertising: "HirdetĂ©sek (AdSense)",
    googleCmp: "Google CMP",
    advertisingDesc: "A hirdetĂ©si hozzĂˇjĂˇrulĂˇst kĂĽlĂ¶n, a Google hozzĂˇjĂˇrulĂˇsi szolgĂˇltatĂˇsain keresztĂĽl kezeljĂĽk, ahol ezek elĂ©rhetĹ‘k.",
    savePreferences: "BeĂˇllĂ­tĂˇsok mentĂ©se",
    cookieSettings: "SĂĽti beĂˇllĂ­tĂˇsok",
  },
  de: {
    ariaLabel: "Datenschutz- und Einwilligungseinstellungen",
    title: "Datenschutzeinstellungen",
    intro: "Wir verwenden notwendige Speicherung, um MatchSignal zu betreiben. Mit Ihrer Zustimmung nutzen wir auĂźerdem Analysen, um die Nutzung der Website zu verstehen und sie zu verbessern. Die Einwilligung fĂĽr Werbung wird separat verwaltet, sofern Google-Einwilligungsdienste verfĂĽgbar sind.",
    customize: "Anpassen",
    necessaryOnly: "Nur notwendige",
    allowAnalytics: "Analysen erlauben",
    customizeTitle: "Datenschutzeinstellungen anpassen",
    close: "SchlieĂźen",
    necessary: "Notwendig",
    alwaysActive: "Immer aktiv",
    necessaryDesc: "Erforderlich fĂĽr Seitennavigation, Sicherheit und das Speichern Ihrer Einwilligungseinstellungen.",
    analytics: "Analysen (GA4)",
    analyticsDesc: "Hilft uns, Website-Traffic, Seitenaufrufe und Funktionsnutzung zu messen und die Leistung zu verbessern.",
    advertising: "Werbung (AdSense)",
    googleCmp: "Google CMP",
    advertisingDesc: "Die Werbeeinwilligung wird separat ĂĽber Google-Einwilligungsdienste verwaltet, sofern verfĂĽgbar.",
    savePreferences: "Einstellungen speichern",
    cookieSettings: "Cookie-Einstellungen",
  },
  fr: {
    ariaLabel: "Choix de confidentialitĂ© et de consentement",
    title: "Choix de confidentialitĂ©",
    intro: "Nous utilisons le stockage nĂ©cessaire au fonctionnement de MatchSignal. Avec votre autorisation, nous utilisons Ă©galement des analyses pour comprendre lâ€™utilisation du site et lâ€™amĂ©liorer. Le consentement publicitaire est gĂ©rĂ© sĂ©parĂ©ment lorsque les services de consentement Google sont disponibles.",
    customize: "Personnaliser",
    necessaryOnly: "NĂ©cessaire uniquement",
    allowAnalytics: "Autoriser les analyses",
    customizeTitle: "Personnaliser les choix de confidentialitĂ©",
    close: "Fermer",
    necessary: "NĂ©cessaire",
    alwaysActive: "Toujours actif",
    necessaryDesc: "NĂ©cessaire pour la navigation, la sĂ©curitĂ© et lâ€™enregistrement de vos prĂ©fĂ©rences de consentement.",
    analytics: "Analyses (GA4)",
    analyticsDesc: "Nous aide Ă  mesurer le trafic, les pages vues et lâ€™utilisation des fonctionnalitĂ©s afin dâ€™amĂ©liorer les performances.",
    advertising: "PublicitĂ© (AdSense)",
    googleCmp: "Google CMP",
    advertisingDesc: "Le consentement publicitaire est gĂ©rĂ© sĂ©parĂ©ment via les services de consentement Google lorsquâ€™ils sont disponibles.",
    savePreferences: "Enregistrer les prĂ©fĂ©rences",
    cookieSettings: "ParamĂ¨tres des cookies",
  },
  es: {
    ariaLabel: "Opciones de privacidad y consentimiento",
    title: "Opciones de privacidad",
    intro: "Utilizamos almacenamiento necesario para el funcionamiento de MatchSignal. Con su permiso, tambiĂ©n utilizamos analĂ­tica para comprender cĂłmo se usa el sitio y mejorarlo. El consentimiento publicitario se gestiona por separado cuando estĂˇn disponibles los servicios de consentimiento de Google.",
    customize: "Personalizar",
    necessaryOnly: "Solo necesario",
    allowAnalytics: "Permitir analĂ­tica",
    customizeTitle: "Personalizar opciones de privacidad",
    close: "Cerrar",
    necessary: "Necesario",
    alwaysActive: "Siempre activo",
    necessaryDesc: "Necesario para la navegaciĂłn, la seguridad y el almacenamiento de sus preferencias de consentimiento.",
    analytics: "AnalĂ­tica (GA4)",
    analyticsDesc: "Nos ayuda a medir el trĂˇfico, las pĂˇginas vistas y el uso de funciones para mejorar el rendimiento.",
    advertising: "Publicidad (AdSense)",
    googleCmp: "Google CMP",
    advertisingDesc: "El consentimiento publicitario se gestiona por separado mediante los servicios de consentimiento de Google cuando estĂˇn disponibles.",
    savePreferences: "Guardar preferencias",
    cookieSettings: "ConfiguraciĂłn de cookies",
  },
  it: {
    ariaLabel: "Scelte sulla privacy e sul consenso",
    title: "Scelte sulla privacy",
    intro: "Utilizziamo lo spazio di archiviazione necessario per il funzionamento di MatchSignal. Con il tuo consenso utilizziamo anche strumenti di analisi per comprendere lâ€™utilizzo del sito e migliorarlo. Il consenso pubblicitario viene gestito separatamente dove sono disponibili i servizi di consenso Google.",
    customize: "Personalizza",
    necessaryOnly: "Solo necessari",
    allowAnalytics: "Consenti analisi",
    customizeTitle: "Personalizza le scelte sulla privacy",
    close: "Chiudi",
    necessary: "Necessari",
    alwaysActive: "Sempre attivi",
    necessaryDesc: "Necessari per la navigazione, la sicurezza e la memorizzazione delle preferenze di consenso.",
    analytics: "Analisi (GA4)",
    analyticsDesc: "Ci aiuta a misurare traffico, visualizzazioni di pagina e utilizzo delle funzionalitĂ  per migliorare le prestazioni.",
    advertising: "PubblicitĂ  (AdSense)",
    googleCmp: "Google CMP",
    advertisingDesc: "Il consenso pubblicitario viene gestito separatamente tramite i servizi di consenso Google dove disponibili.",
    savePreferences: "Salva preferenze",
    cookieSettings: "Impostazioni cookie",
  },
  pt: {
    ariaLabel: "OpĂ§Ăµes de privacidade e consentimento",
    title: "OpĂ§Ăµes de privacidade",
    intro: "Utilizamos armazenamento necessĂˇrio para operar o MatchSignal. Com a sua permissĂŁo, tambĂ©m utilizamos anĂˇlises para compreender como o site Ă© utilizado e melhorĂˇ-lo. O consentimento de publicidade Ă© gerido separadamente quando os serviĂ§os de consentimento da Google estĂŁo disponĂ­veis.",
    customize: "Personalizar",
    necessaryOnly: "Apenas necessĂˇrios",
    allowAnalytics: "Permitir anĂˇlises",
    customizeTitle: "Personalizar opĂ§Ăµes de privacidade",
    close: "Fechar",
    necessary: "NecessĂˇrio",
    alwaysActive: "Sempre ativo",
    necessaryDesc: "NecessĂˇrio para navegaĂ§ĂŁo, seguranĂ§a e armazenamento das suas preferĂŞncias de consentimento.",
    analytics: "AnĂˇlises (GA4)",
    analyticsDesc: "Ajuda-nos a medir trĂˇfego, visualizaĂ§Ăµes de pĂˇginas e utilizaĂ§ĂŁo de funcionalidades para melhorar o desempenho.",
    advertising: "Publicidade (AdSense)",
    googleCmp: "Google CMP",
    advertisingDesc: "O consentimento de publicidade Ă© gerido separadamente atravĂ©s dos serviĂ§os de consentimento da Google, quando disponĂ­veis.",
    savePreferences: "Guardar preferĂŞncias",
    cookieSettings: "DefiniĂ§Ăµes de cookies",
  },
  ar: {
    ariaLabel: "Ř®ŮŠŘ§Ř±Ř§ŘŞ Ř§Ů„Ř®ŘµŮŘµŮŠŘ© ŮŘ§Ů„Ů…ŮŘ§ŮŮ‚Ř©",
    title: "Ř®ŮŠŘ§Ř±Ř§ŘŞ Ř§Ů„Ř®ŘµŮŘµŮŠŘ©",
    intro: "Ů†ŘłŘŞŘ®ŘŻŮ… Ř§Ů„ŘŞŘ®Ř˛ŮŠŮ† Ř§Ů„Ř¶Ř±ŮŘ±ŮŠ Ů„ŘŞŘ´ŘşŮŠŮ„ MatchSignal. ŮŘ¨Ů…ŮŘ§ŮŮ‚ŘŞŮ Ů†ŘłŘŞŘ®ŘŻŮ… ŘŁŮŠŘ¶Ů‹Ř§ Ř§Ů„ŘŞŘ­Ů„ŮŠŮ„Ř§ŘŞ Ů„ŮŮ‡Ů… ŮŮŠŮŮŠŘ© Ř§ŘłŘŞŘ®ŘŻŘ§Ů… Ř§Ů„Ů…ŮŮ‚Řą ŮŘŞŘ­ŘłŮŠŮ†Ů‡. ŘŞŘŞŮ… ŘĄŘŻŘ§Ř±Ř© Ř§Ů„Ů…ŮŘ§ŮŮ‚Ř© ŘąŮ„Ů‰ Ř§Ů„ŘĄŘąŮ„Ř§Ů†Ř§ŘŞ Ř¨Ř´ŮŮ„ Ů…Ů†ŮŘµŮ„ Ř­ŮŠŘ« ŘŞŘŞŮŮŘ± Ř®ŘŻŮ…Ř§ŘŞ Ů…ŮŘ§ŮŮ‚Ř© Google.",
    customize: "ŘŞŘ®ŘµŮŠŘµ",
    necessaryOnly: "Ř§Ů„Ř¶Ř±ŮŘ±ŮŠ ŮŮ‚Ř·",
    allowAnalytics: "Ř§Ů„ŘłŮ…Ř§Ř­ Ř¨Ř§Ů„ŘŞŘ­Ů„ŮŠŮ„Ř§ŘŞ",
    customizeTitle: "ŘŞŘ®ŘµŮŠŘµ Ř®ŮŠŘ§Ř±Ř§ŘŞ Ř§Ů„Ř®ŘµŮŘµŮŠŘ©",
    close: "ŘĄŘşŮ„Ř§Ů‚",
    necessary: "Ř¶Ř±ŮŘ±ŮŠ",
    alwaysActive: "Ů†Ř´Ř· ŘŻŘ§Ř¦Ů…Ů‹Ř§",
    necessaryDesc: "Ů…Ř·Ů„ŮŘ¨ Ů„Ů„ŘŞŮ†Ů‚Ů„ ŮŮŠ Ř§Ů„Ů…ŮŮ‚Řą ŮŘ§Ů„ŘŁŮ…Ř§Ů† ŮŘŞŘ®Ř˛ŮŠŮ† ŘŞŮŘ¶ŮŠŮ„Ř§ŘŞ Ř§Ů„Ů…ŮŘ§ŮŮ‚Ř©.",
    analytics: "Ř§Ů„ŘŞŘ­Ů„ŮŠŮ„Ř§ŘŞ (GA4)",
    analyticsDesc: "ŮŠŘłŘ§ŘąŘŻŮ†Ř§ ŘąŮ„Ů‰ Ů‚ŮŠŘ§Řł Ř­Ř±ŮŘ© Ř§Ů„Ů…ŮŮ‚Řą ŮŮ…Ř´Ř§Ů‡ŘŻŘ§ŘŞ Ř§Ů„ŘµŮŘ­Ř§ŘŞ ŮŘ§ŘłŘŞŘ®ŘŻŘ§Ů… Ř§Ů„Ů…ŮŠŘ˛Ř§ŘŞ Ů„ŘŞŘ­ŘłŮŠŮ† Ř§Ů„ŘŁŘŻŘ§Řˇ.",
    advertising: "Ř§Ů„ŘĄŘąŮ„Ř§Ů†Ř§ŘŞ (AdSense)",
    googleCmp: "Google CMP",
    advertisingDesc: "ŘŞŘŞŮ… ŘĄŘŻŘ§Ř±Ř© Ř§Ů„Ů…ŮŘ§ŮŮ‚Ř© ŘąŮ„Ů‰ Ř§Ů„ŘĄŘąŮ„Ř§Ů†Ř§ŘŞ Ř¨Ř´ŮŮ„ Ů…Ů†ŮŘµŮ„ ŘąŘ¨Ř± Ř®ŘŻŮ…Ř§ŘŞ Ů…ŮŘ§ŮŮ‚Ř© Google Ř­ŮŠŘ« ŘŞŘŞŮŮŘ±.",
    savePreferences: "Ř­ŮŘ¸ Ř§Ů„ŘŞŮŘ¶ŮŠŮ„Ř§ŘŞ",
    cookieSettings: "ŘĄŘąŘŻŘ§ŘŻŘ§ŘŞ Ů…Ů„ŮŘ§ŘŞ Ř§Ů„Ř§Ř±ŘŞŘ¨Ř§Ř·",
  },
  zh: {
    ariaLabel: "éšç§ä¸ŽĺŚć„Źé€‰éˇą",
    title: "éšç§é€‰éˇą",
    intro: "ć‘ä»¬ä˝żç”¨ĺż…č¦çš„ĺ­ĺ‚¨ĺŠźč˝ćťĄčżčˇŚ MatchSignală€‚ç»Źć‚¨č®¸ĺŹŻďĽŚć‘ä»¬čżäĽšä˝żç”¨ĺ†ćžĺ·Ąĺ…·ćťĄäş†č§Łç˝‘ç«™çš„ä˝żç”¨ć…ĺ†µĺą¶ĺŠ ä»Ąć”ąčż›ă€‚ĺś¨ Google ĺŚć„ŹćśŤĺŠˇĺŹŻç”¨çš„ĺś°ĺŚşďĽŚĺążĺ‘ŠĺŚć„Źĺ°†ĺŤ•ç‹¬ç®ˇç†ă€‚",
    customize: "č‡Şĺ®šäą‰",
    necessaryOnly: "ä»…ĺż…č¦éˇą",
    allowAnalytics: "ĺ…č®¸ĺ†ćž",
    customizeTitle: "č‡Şĺ®šäą‰éšç§é€‰éˇą",
    close: "ĺ…łé—­",
    necessary: "ĺż…č¦",
    alwaysActive: "ĺ§‹ç»ĺŻç”¨",
    necessaryDesc: "ç˝‘ç«™ĺŻĽčŞă€ĺ®‰ĺ…¨ä»ĄĺŹŠäżťĺ­ć‚¨çš„ĺŚć„ŹĺŹĺĄ˝ć‰€ĺż…éś€ă€‚",
    analytics: "ĺ†ćž (GA4)",
    analyticsDesc: "ĺ¸®ĺŠ©ć‘ä»¬čˇˇé‡Źç˝‘ç«™ćµé‡Źă€éˇµéť˘ćµŹč§ĺ’ŚĺŠźč˝ä˝żç”¨ć…ĺ†µďĽŚä»Ąć”ąĺ–„ć€§č˝ă€‚",
    advertising: "ĺążĺ‘Š (AdSense)",
    googleCmp: "Google CMP",
    advertisingDesc: "ĺś¨ĺŹŻç”¨ĺś°ĺŚşďĽŚĺążĺ‘ŠĺŚć„Źé€ščż‡ Google ĺŚć„ŹćśŤĺŠˇĺŤ•ç‹¬ç®ˇç†ă€‚",
    savePreferences: "äżťĺ­ĺŹĺĄ˝",
    cookieSettings: "Cookie č®ľç˝®",
  },
  ja: {
    ariaLabel: "ă—ă©ă‚¤ăă‚·ăĽă¨ĺŚć„Źă®é¸ćŠž",
    title: "ă—ă©ă‚¤ăă‚·ăĽč¨­ĺ®š",
    intro: "MatchSignal ă®é‹ĺ–¶ă«ĺż…č¦ăŞă‚ąăă¬ăĽă‚¸ă‚’ä˝żç”¨ă—ăľă™ă€‚č¨±ĺŹŻă„ăźă ă„ăźĺ ´ĺă€ă‚µă‚¤ăă®ĺ©ç”¨çŠ¶ćłă‚’ćŠŠćŹˇă—ă¦ć”ąĺ–„ă™ă‚‹ăźă‚ă«ĺ†ćžă‚‚ä˝żç”¨ă—ăľă™ă€‚ĺşĺ‘Šă«é–˘ă™ă‚‹ĺŚć„ŹăŻă€Google ă®ĺŚć„Źă‚µăĽă“ă‚ąăŚĺ©ç”¨ă§ăŤă‚‹ĺ ´ĺă«ĺĄé€”ç®ˇç†ă•ă‚Śăľă™ă€‚",
    customize: "ă‚«ă‚ąă‚żăžă‚¤ă‚ş",
    necessaryOnly: "ĺż…č¦ăŞă‚‚ă®ă®ăż",
    allowAnalytics: "ĺ†ćžă‚’č¨±ĺŹŻ",
    customizeTitle: "ă—ă©ă‚¤ăă‚·ăĽč¨­ĺ®šă‚’ă‚«ă‚ąă‚żăžă‚¤ă‚ş",
    close: "é–‰ăă‚‹",
    necessary: "ĺż…é ",
    alwaysActive: "ĺ¸¸ă«ćś‰ĺŠą",
    necessaryDesc: "ă‚µă‚¤ăă®ăŠă“ă‚˛ăĽă‚·ă§ăłă€ă‚»ă‚­ăĄăŞă†ă‚Łă€ĺŚć„Źč¨­ĺ®šă®äżťĺ­ă«ĺż…č¦ă§ă™ă€‚",
    analytics: "ĺ†ćž (GA4)",
    analyticsDesc: "ă‚µă‚¤ăă®ăă©ă•ă‚Łăă‚Żă€ăšăĽă‚¸ă“ăĄăĽă€ć©źč˝ă®ĺ©ç”¨çŠ¶ćłă‚’ć¸¬ĺ®šă—ă€ă‘ă•ă‚©ăĽăžăłă‚ąă®ć”ąĺ–„ă«ĺ˝ąç«‹ă¦ăľă™ă€‚",
    advertising: "ĺşĺ‘Š (AdSense)",
    googleCmp: "Google CMP",
    advertisingDesc: "ĺ©ç”¨ĺŹŻč˝ăŞĺ ´ĺă€ĺşĺ‘Šă®ĺŚć„ŹăŻ Google ă®ĺŚć„Źă‚µăĽă“ă‚ąă‚’é€šăă¦ĺĄé€”ç®ˇç†ă•ă‚Śăľă™ă€‚",
    savePreferences: "č¨­ĺ®šă‚’äżťĺ­",
    cookieSettings: "Cookie č¨­ĺ®š",
  },
  hi: {
    ariaLabel: "ŕ¤—ŕĄ‹ŕ¤Şŕ¤¨ŕĄ€ŕ¤Żŕ¤¤ŕ¤ľ ŕ¤”ŕ¤° ŕ¤¸ŕ¤ąŕ¤®ŕ¤¤ŕ¤ż ŕ¤µŕ¤żŕ¤•ŕ¤˛ŕĄŤŕ¤Ş",
    title: "ŕ¤—ŕĄ‹ŕ¤Şŕ¤¨ŕĄ€ŕ¤Żŕ¤¤ŕ¤ľ ŕ¤µŕ¤żŕ¤•ŕ¤˛ŕĄŤŕ¤Ş",
    intro: "MatchSignal ŕ¤•ŕĄ‹ ŕ¤¸ŕ¤‚ŕ¤šŕ¤ľŕ¤˛ŕ¤żŕ¤¤ ŕ¤•ŕ¤°ŕ¤¨ŕĄ‡ ŕ¤•ŕĄ‡ ŕ¤˛ŕ¤żŕ¤Ź ŕ¤ąŕ¤® ŕ¤†ŕ¤µŕ¤¶ŕĄŤŕ¤Żŕ¤• ŕ¤¸ŕĄŤŕ¤źŕĄ‹ŕ¤°ŕĄ‡ŕ¤ś ŕ¤•ŕ¤ľ ŕ¤‰ŕ¤Şŕ¤ŻŕĄ‹ŕ¤— ŕ¤•ŕ¤°ŕ¤¤ŕĄ‡ ŕ¤ąŕĄŕ¤‚ŕĄ¤ ŕ¤†ŕ¤Şŕ¤•ŕĄ€ ŕ¤…ŕ¤¨ŕĄŕ¤®ŕ¤¤ŕ¤ż ŕ¤¸ŕĄ‡ ŕ¤ąŕ¤® ŕ¤¸ŕ¤ľŕ¤‡ŕ¤ź ŕ¤•ŕĄ‡ ŕ¤‰ŕ¤Şŕ¤ŻŕĄ‹ŕ¤— ŕ¤•ŕĄ‹ ŕ¤¸ŕ¤®ŕ¤ťŕ¤¨ŕĄ‡ ŕ¤”ŕ¤° ŕ¤‰ŕ¤¸ŕĄ‡ ŕ¤¬ŕĄ‡ŕ¤ąŕ¤¤ŕ¤° ŕ¤¬ŕ¤¨ŕ¤ľŕ¤¨ŕĄ‡ ŕ¤•ŕĄ‡ ŕ¤˛ŕ¤żŕ¤Ź ŕ¤Źŕ¤¨ŕ¤ľŕ¤˛ŕ¤żŕ¤źŕ¤żŕ¤•ŕĄŤŕ¤¸ ŕ¤•ŕ¤ľ ŕ¤­ŕĄ€ ŕ¤‰ŕ¤Şŕ¤ŻŕĄ‹ŕ¤— ŕ¤•ŕ¤°ŕ¤¤ŕĄ‡ ŕ¤ąŕĄŕ¤‚ŕĄ¤ ŕ¤śŕ¤ąŕ¤ľŕ¤ Google ŕ¤•ŕĄ€ ŕ¤¸ŕ¤ąŕ¤®ŕ¤¤ŕ¤ż ŕ¤¸ŕĄ‡ŕ¤µŕ¤ľŕ¤Źŕ¤ ŕ¤‰ŕ¤Şŕ¤˛ŕ¤¬ŕĄŤŕ¤§ ŕ¤ąŕĄŕ¤‚, ŕ¤µŕ¤ąŕ¤ľŕ¤ ŕ¤µŕ¤żŕ¤śŕĄŤŕ¤žŕ¤ľŕ¤Şŕ¤¨ ŕ¤¸ŕ¤ąŕ¤®ŕ¤¤ŕ¤ż ŕ¤…ŕ¤˛ŕ¤— ŕ¤¸ŕĄ‡ ŕ¤ŞŕĄŤŕ¤°ŕ¤¬ŕ¤‚ŕ¤§ŕ¤żŕ¤¤ ŕ¤•ŕĄ€ ŕ¤śŕ¤ľŕ¤¤ŕĄ€ ŕ¤ąŕĄŕĄ¤",
    customize: "ŕ¤…ŕ¤¨ŕĄŕ¤•ŕĄ‚ŕ¤˛ŕ¤żŕ¤¤ ŕ¤•ŕ¤°ŕĄ‡ŕ¤‚",
    necessaryOnly: "ŕ¤•ŕĄ‡ŕ¤µŕ¤˛ ŕ¤†ŕ¤µŕ¤¶ŕĄŤŕ¤Żŕ¤•",
    allowAnalytics: "ŕ¤Źŕ¤¨ŕ¤ľŕ¤˛ŕ¤żŕ¤źŕ¤żŕ¤•ŕĄŤŕ¤¸ ŕ¤•ŕĄ€ ŕ¤…ŕ¤¨ŕĄŕ¤®ŕ¤¤ŕ¤ż ŕ¤¦ŕĄ‡ŕ¤‚",
    customizeTitle: "ŕ¤—ŕĄ‹ŕ¤Şŕ¤¨ŕĄ€ŕ¤Żŕ¤¤ŕ¤ľ ŕ¤µŕ¤żŕ¤•ŕ¤˛ŕĄŤŕ¤Ş ŕ¤…ŕ¤¨ŕĄŕ¤•ŕĄ‚ŕ¤˛ŕ¤żŕ¤¤ ŕ¤•ŕ¤°ŕĄ‡ŕ¤‚",
    close: "ŕ¤¬ŕ¤‚ŕ¤¦ ŕ¤•ŕ¤°ŕĄ‡ŕ¤‚",
    necessary: "ŕ¤†ŕ¤µŕ¤¶ŕĄŤŕ¤Żŕ¤•",
    alwaysActive: "ŕ¤ąŕ¤®ŕĄ‡ŕ¤¶ŕ¤ľ ŕ¤¸ŕ¤•ŕĄŤŕ¤°ŕ¤żŕ¤Ż",
    necessaryDesc: "ŕ¤¸ŕ¤ľŕ¤‡ŕ¤ź ŕ¤¨ŕĄ‡ŕ¤µŕ¤żŕ¤—ŕĄ‡ŕ¤¶ŕ¤¨, ŕ¤¸ŕĄŕ¤°ŕ¤•ŕĄŤŕ¤·ŕ¤ľ ŕ¤”ŕ¤° ŕ¤†ŕ¤Şŕ¤•ŕĄ€ ŕ¤¸ŕ¤ąŕ¤®ŕ¤¤ŕ¤ż ŕ¤ŞŕĄŤŕ¤°ŕ¤ľŕ¤Ąŕ¤®ŕ¤żŕ¤•ŕ¤¤ŕ¤ľŕ¤Źŕ¤ ŕ¤¸ŕ¤ąŕĄ‡ŕ¤śŕ¤¨ŕĄ‡ ŕ¤•ŕĄ‡ ŕ¤˛ŕ¤żŕ¤Ź ŕ¤†ŕ¤µŕ¤¶ŕĄŤŕ¤Żŕ¤•ŕĄ¤",
    analytics: "ŕ¤Źŕ¤¨ŕ¤ľŕ¤˛ŕ¤żŕ¤źŕ¤żŕ¤•ŕĄŤŕ¤¸ (GA4)",
    analyticsDesc: "ŕ¤¸ŕ¤ľŕ¤‡ŕ¤ź ŕ¤źŕĄŤŕ¤°ŕĄŕ¤«ŕ¤żŕ¤•, ŕ¤ŞŕĄ‡ŕ¤ś ŕ¤µŕĄŤŕ¤ŻŕĄ‚ ŕ¤”ŕ¤° ŕ¤«ŕĄ€ŕ¤šŕ¤° ŕ¤‰ŕ¤Şŕ¤ŻŕĄ‹ŕ¤— ŕ¤•ŕĄ‹ ŕ¤®ŕ¤ľŕ¤Şŕ¤¨ŕĄ‡ ŕ¤®ŕĄ‡ŕ¤‚ ŕ¤®ŕ¤¦ŕ¤¦ ŕ¤•ŕ¤°ŕ¤¤ŕ¤ľ ŕ¤ąŕĄ ŕ¤¤ŕ¤ľŕ¤•ŕ¤ż ŕ¤ŞŕĄŤŕ¤°ŕ¤¦ŕ¤°ŕĄŤŕ¤¶ŕ¤¨ ŕ¤¬ŕĄ‡ŕ¤ąŕ¤¤ŕ¤° ŕ¤•ŕ¤żŕ¤Żŕ¤ľ ŕ¤śŕ¤ľ ŕ¤¸ŕ¤•ŕĄ‡ŕĄ¤",
    advertising: "ŕ¤µŕ¤żŕ¤śŕĄŤŕ¤žŕ¤ľŕ¤Şŕ¤¨ (AdSense)",
    googleCmp: "Google CMP",
    advertisingDesc: "ŕ¤śŕ¤ąŕ¤ľŕ¤ ŕ¤‰ŕ¤Şŕ¤˛ŕ¤¬ŕĄŤŕ¤§ ŕ¤ąŕĄ‹, ŕ¤µŕ¤żŕ¤śŕĄŤŕ¤žŕ¤ľŕ¤Şŕ¤¨ ŕ¤¸ŕ¤ąŕ¤®ŕ¤¤ŕ¤ż Google ŕ¤•ŕĄ€ ŕ¤¸ŕ¤ąŕ¤®ŕ¤¤ŕ¤ż ŕ¤¸ŕĄ‡ŕ¤µŕ¤ľŕ¤“ŕ¤‚ ŕ¤•ŕĄ‡ ŕ¤®ŕ¤ľŕ¤§ŕĄŤŕ¤Żŕ¤® ŕ¤¸ŕĄ‡ ŕ¤…ŕ¤˛ŕ¤— ŕ¤¸ŕĄ‡ ŕ¤ŞŕĄŤŕ¤°ŕ¤¬ŕ¤‚ŕ¤§ŕ¤żŕ¤¤ ŕ¤•ŕĄ€ ŕ¤śŕ¤ľŕ¤¤ŕĄ€ ŕ¤ąŕĄŕĄ¤",
    savePreferences: "ŕ¤ŞŕĄŤŕ¤°ŕ¤ľŕ¤Ąŕ¤®ŕ¤żŕ¤•ŕ¤¤ŕ¤ľŕ¤Źŕ¤ ŕ¤¸ŕ¤ąŕĄ‡ŕ¤śŕĄ‡ŕ¤‚",
    cookieSettings: "Cookie ŕ¤¸ŕĄ‡ŕ¤źŕ¤żŕ¤‚ŕ¤—ŕĄŤŕ¤¸",
  },
} as const;
