/**
 * Generated by scripts/generate-social-video-copy.ts.
 * Static imports keep video content traceable in Next.js/Vercel bundles.
 */
export const VIDEO_CONTENT_PACKAGE_VALUES: readonly unknown[] = [];
