import videoPackage0 from "../../../../data/social-videos/0818.json";
import videoPackage1 from "../../../../data/social-videos/0824.json";
import videoPackage2 from "../../../../data/social-videos/0825.json";
import videoPackage3 from "../../../../data/social-videos/0826.json";
import videoPackage4 from "../../../../data/social-videos/0827.json";
import videoPackage5 from "../../../../data/social-videos/0828.json";
import videoPackage6 from "../../../../data/social-videos/0829.json";
import videoPackage7 from "../../../../data/social-videos/0830.json";
import videoPackage8 from "../../../../data/social-videos/0831.json";

/**
 * Generated by scripts/generate-social-video-copy.ts.
 * Static imports keep video content traceable in Next.js/Vercel bundles.
 */
export const VIDEO_CONTENT_PACKAGE_VALUES: readonly unknown[] = [
  videoPackage0,
  videoPackage1,
  videoPackage2,
  videoPackage3,
  videoPackage4,
  videoPackage5,
  videoPackage6,
  videoPackage7,
  videoPackage8,
];
