import videoPackage0 from "../../../../data/social-videos/0818.json";
import videoPackage1 from "../../../../data/social-videos/0824.json";
import videoPackage2 from "../../../../data/social-videos/0825.json";
import videoPackage3 from "../../../../data/social-videos/0826.json";
import videoPackage4 from "../../../../data/social-videos/0827.json";
import videoPackage5 from "../../../../data/social-videos/0828.json";
import videoPackage6 from "../../../../data/social-videos/0829.json";
import videoPackage7 from "../../../../data/social-videos/0830.json";
import videoPackage8 from "../../../../data/social-videos/0831.json";
import videoPackage9 from "../../../../data/social-videos/1.json";
import videoPackage10 from "../../../../data/social-videos/10.json";
import videoPackage11 from "../../../../data/social-videos/11.json";
import videoPackage12 from "../../../../data/social-videos/12.json";
import videoPackage13 from "../../../../data/social-videos/13.json";
import videoPackage14 from "../../../../data/social-videos/14.json";
import videoPackage15 from "../../../../data/social-videos/15.json";
import videoPackage16 from "../../../../data/social-videos/16.json";
import videoPackage17 from "../../../../data/social-videos/17.json";
import videoPackage18 from "../../../../data/social-videos/18.json";
import videoPackage19 from "../../../../data/social-videos/19.json";
import videoPackage20 from "../../../../data/social-videos/2.json";
import videoPackage21 from "../../../../data/social-videos/20.json";
import videoPackage22 from "../../../../data/social-videos/21.json";
import videoPackage23 from "../../../../data/social-videos/22.json";
import videoPackage24 from "../../../../data/social-videos/23.json";
import videoPackage25 from "../../../../data/social-videos/24.json";
import videoPackage26 from "../../../../data/social-videos/25.json";
import videoPackage27 from "../../../../data/social-videos/26.json";
import videoPackage28 from "../../../../data/social-videos/27.json";
import videoPackage29 from "../../../../data/social-videos/28.json";
import videoPackage30 from "../../../../data/social-videos/29.json";
import videoPackage31 from "../../../../data/social-videos/3.json";
import videoPackage32 from "../../../../data/social-videos/30.json";
import videoPackage33 from "../../../../data/social-videos/31.json";
import videoPackage34 from "../../../../data/social-videos/32.json";
import videoPackage35 from "../../../../data/social-videos/33.json";
import videoPackage36 from "../../../../data/social-videos/34.json";
import videoPackage37 from "../../../../data/social-videos/35.json";
import videoPackage38 from "../../../../data/social-videos/36.json";
import videoPackage39 from "../../../../data/social-videos/37.json";
import videoPackage40 from "../../../../data/social-videos/38.json";
import videoPackage41 from "../../../../data/social-videos/39.json";
import videoPackage42 from "../../../../data/social-videos/4.json";
import videoPackage43 from "../../../../data/social-videos/40.json";
import videoPackage44 from "../../../../data/social-videos/41.json";
import videoPackage45 from "../../../../data/social-videos/42.json";
import videoPackage46 from "../../../../data/social-videos/43.json";
import videoPackage47 from "../../../../data/social-videos/44.json";
import videoPackage48 from "../../../../data/social-videos/45.json";
import videoPackage49 from "../../../../data/social-videos/46.json";
import videoPackage50 from "../../../../data/social-videos/47.json";
import videoPackage51 from "../../../../data/social-videos/48.json";
import videoPackage52 from "../../../../data/social-videos/49.json";
import videoPackage53 from "../../../../data/social-videos/5.json";
import videoPackage54 from "../../../../data/social-videos/50.json";
import videoPackage55 from "../../../../data/social-videos/51.json";
import videoPackage56 from "../../../../data/social-videos/52.json";
import videoPackage57 from "../../../../data/social-videos/53.json";
import videoPackage58 from "../../../../data/social-videos/54.json";
import videoPackage59 from "../../../../data/social-videos/6.json";
import videoPackage60 from "../../../../data/social-videos/7.json";
import videoPackage61 from "../../../../data/social-videos/8.json";
import videoPackage62 from "../../../../data/social-videos/9.json";

/**
 * Generated by scripts/generate-social-video-copy.ts.
 * Static imports keep video content traceable in Next.js/Vercel bundles.
 */
export const VIDEO_CONTENT_PACKAGE_VALUES: readonly unknown[] = [
  videoPackage0,
  videoPackage1,
  videoPackage2,
  videoPackage3,
  videoPackage4,
  videoPackage5,
  videoPackage6,
  videoPackage7,
  videoPackage8,
  videoPackage9,
  videoPackage10,
  videoPackage11,
  videoPackage12,
  videoPackage13,
  videoPackage14,
  videoPackage15,
  videoPackage16,
  videoPackage17,
  videoPackage18,
  videoPackage19,
  videoPackage20,
  videoPackage21,
  videoPackage22,
  videoPackage23,
  videoPackage24,
  videoPackage25,
  videoPackage26,
  videoPackage27,
  videoPackage28,
  videoPackage29,
  videoPackage30,
  videoPackage31,
  videoPackage32,
  videoPackage33,
  videoPackage34,
  videoPackage35,
  videoPackage36,
  videoPackage37,
  videoPackage38,
  videoPackage39,
  videoPackage40,
  videoPackage41,
  videoPackage42,
  videoPackage43,
  videoPackage44,
  videoPackage45,
  videoPackage46,
  videoPackage47,
  videoPackage48,
  videoPackage49,
  videoPackage50,
  videoPackage51,
  videoPackage52,
  videoPackage53,
  videoPackage54,
  videoPackage55,
  videoPackage56,
  videoPackage57,
  videoPackage58,
  videoPackage59,
  videoPackage60,
  videoPackage61,
  videoPackage62,
];
