import { loadEnvConfig } from "@next/env";
import { promises as fs } from "node:fs";
import path from "node:path";

import { generateVideoContentPackage } from "../app/lib/social/video/copy-generate";
import { generateVideoCopyWithGroq } from "../app/lib/social/video/copy-groq";
import { parseVideoContentInput } from "../app/lib/social/video/copy-validate";

const INPUT_DIRECTORY = path.join(process.cwd(), "data", "social-video-inputs");
const OUTPUT_DIRECTORY = path.join(process.cwd(), "data", "social-videos");
const INDEX_PATH = path.join(
  process.cwd(),
  "app",
  "lib",
  "social",
  "video",
  "content-index.ts"
);

function readIdArgument(argv: readonly string[]): string {
  const idIndex = argv.indexOf("--id");
  const id = idIndex >= 0 ? argv[idIndex + 1] : undefined;
  if (!id || !/^[a-zA-Z0-9][a-zA-Z0-9_-]*$/.test(id)) {
    throw new Error("usage: npm run social-video:generate -- --id <video-id>");
  }
  return id;
}

async function updateStaticIndex() {
  await fs.mkdir(OUTPUT_DIRECTORY, { recursive: true });
  const files = (await fs.readdir(OUTPUT_DIRECTORY))
    .filter((file) => /^[a-zA-Z0-9][a-zA-Z0-9_-]*\.json$/.test(file))
    .sort((left, right) => left.localeCompare(right));
  const imports = files.map(
    (file, index) =>
      `import videoPackage${index} from "../../../../data/social-videos/${file}";`
  );
  const values = files.map((_, index) => `videoPackage${index}`).join(", ");
  const content = `${imports.join("\n")}${imports.length ? "\n\n" : ""}/**\n * Generated by scripts/generate-social-video-copy.ts.\n * Static imports keep video content traceable in Next.js/Vercel bundles.\n */\nexport const VIDEO_CONTENT_PACKAGE_VALUES: readonly unknown[] = [${values}];\n`;
  await fs.writeFile(INDEX_PATH, content, "utf8");
}

async function main() {
  loadEnvConfig(process.cwd());
  const id = readIdArgument(process.argv.slice(2));
  const inputPath = path.join(INPUT_DIRECTORY, `${id}.json`);
  const outputPath = path.join(OUTPUT_DIRECTORY, `${id}.json`);
  const input = parseVideoContentInput(JSON.parse(await fs.readFile(inputPath, "utf8")));
  if (input.id !== id) throw new Error(`input ID ${input.id} does not match --id ${id}`);

  if (!process.env.GROQ_API_KEY) {
    console.log(
      JSON.stringify({
        id,
        generationStatus: "pending",
        validation: "NOT_RUN",
        targetCount: 0,
        outputPath,
        reason: "GROQ_API_KEY is unavailable",
      })
    );
    return;
  }

  const outcome = await generateVideoContentPackage({
    input,
    generate: async (prompt) => (await generateVideoCopyWithGroq({ prompt })).copy,
  });
  await fs.mkdir(OUTPUT_DIRECTORY, { recursive: true });
  await fs.writeFile(outputPath, `${JSON.stringify(outcome.contentPackage, null, 2)}\n`, "utf8");
  await updateStaticIndex();

  const targetCount =
    outcome.contentPackage.platforms.instagram.targets.length +
    outcome.contentPackage.platforms.facebook.targets.length +
    outcome.contentPackage.platforms.youtube.targets.length;
  console.log(
    JSON.stringify({
      id,
      generationStatus: outcome.contentPackage.status,
      model: outcome.contentPackage.generation.model,
      validation: outcome.validationErrors.length === 0 ? "PASS" : "FAIL",
      targetCount,
      generationCalls: outcome.generationCalls,
      repaired: outcome.repaired,
      outputPath,
    })
  );
  if (outcome.contentPackage.status === "rejected") process.exitCode = 1;
}

main().catch((error) => {
  console.error(
    JSON.stringify({
      generationStatus: "failed",
      error: error instanceof Error ? error.message : "unknown generation failure",
    })
  );
  process.exitCode = 1;
});
