export const DAY_PRIORITY: Record<string, string[]> = {
  monday: [
    "MLB",
    "Tennis",
    "La Liga",
    "Serie A",
    "Bundesliga",
    "Ligue 1",
    "NHL",
    "NBA",
    "Club Friendlies",
    "MMA",
    "Boxing",
  ],
  tuesday: [
    "Champions League",
    "Champions League Qualification",
    "Europa League",
    "Conference League",
    "Conference League Qualification",
    "MLB",
    "NBA",
    "NHL",
    "Tennis",
    "MMA",
    "Boxing",
  ],
  wednesday: [
    "Champions League",
    "Champions League Qualification",
    "Europa League",
    "Conference League",
    "MLB",
    "NBA",
    "NHL",
    "Tennis",
    "MMA",
    "Boxing",
  ],
  thursday: [
    "Europa League",
    "Conference League",
    "Champions League",
    "Champions League Qualification",
    "MLB",
    "NBA",
    "NHL",
    "Tennis",
    "Boxing",
    "MMA",
  ],
  friday: [
    "Bundesliga",
    "Ligue 1",
    "La Liga",
    "Premier League",
    "MLB",
    "NBA",
    "NHL",
    "Tennis",
    "Club Friendlies",
    "MMA",
    "Boxing",
  ],
  saturday: [
    "Premier League",
    "Bundesliga",
    "Serie A",
    "La Liga",
    "Ligue 1",
    "MLB",
    "NBA",
    "NHL",
    "Tennis",
    "MMA",
    "Boxing",
  ],
  sunday: [
    "Premier League",
    "La Liga",
    "Serie A",
    "Bundesliga",
    "Ligue 1",
    "MLB",
    "NBA",
    "NHL",
    "Tennis",
    "MMA",
    "Boxing",
  ],
};

export function getPriorityKey(sport: string, league: string) {
  if (sport === "Football") return league;
  if (sport === "MMA") {
    if (/boxing/i.test(league)) return "Boxing";
    return "MMA";
  }
  return sport;
}